### ISSUE TITLE
Dynamic slides

### ISSUE THREAD

**Issue by rickysullivan** [alvarotrigo/react-fullpage#153]
### Description
I've built a FP slider that dynamically changes the amount of slides in a section based on the size of the device.

The larger the screen, the more form fields can fit per slide.

This works when initially rendering. However, I want to rebuild the slider when the viewport changes. What would the best approach be?

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/s/react-fullpagejs-example-h4bcm

### Steps to reproduce it
1. Open Codebox sample.
2. Resize browser.
3. Watch it burn.

### Versions 
All latest browsers, macOS, MacMini

**Comment by alvarotrigo** [comment]
Have you taken a look at the example included in the project that allows to add and remove sections?

Just keep track of the number of sections / slides in the state property and update the object with the new number of sections / slides:

https://github.com/alvarotrigo/react-fullpage/blob/89c507ab7e7206603720c234dd61882589de7bfa/examples/react/src/index.js#L54-L77

**Comment by rickysullivan** [comment]
I'm doing that. Did you see the codesandbox?

**Comment by alvarotrigo** [comment]
@rickysullivan can you please reduce the code the the bare minimum? Seems like there's a lot of code in there that is not strictly related with the issue.
Perhaps you can try forking and updating [this codesandbox](https://codesandbox.io/s/m34yq5q0qx)?

If you can, use a click action instead of a viewport resize to fire your change in the DOM.

**Comment by alvarotrigo** [comment]
> I'm doing that. Did you see the codesandbox?

There's a lot of code in there and plenty of external dependencies to fullPage.js.
Make sure to isolated the scenario first by removing all external dependencies and using as little code as possible. Use empty sections with a single heading too.
Then fire the action on a butotn click instead of a viewport resize.

That would make things easier to test :)
