### ISSUE TITLE
How to pass functions when the slides are being converted to responsiveSlides

### ISSUE THREAD

**Issue by danielimmke** [alvarotrigo/react-fullpage#20]
I have an issue with scrolling through slides on mobile, so I bought the responsiveSlides extension. The problem is that fullpage.JS converts the markup and none of the onClick methods I pass seem to go with it. Any ideas?

**Comment by cmswalker** [comment]
Could you provide an example?

**Comment by alvarotrigo** [comment]
> Can I do a google hangouts to show you? The codebase is somewhat complex and I could show you a lot easier than tell you.

Ideally you should be able to create an isolated reproduction in order to report the error.
See my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

In any case, those click events, are they using delegation? 
Will they work even though you change the DOM or you apply them dynamically in new created elements?
That's probably the issue here, as the Responsive Slides extension modifies the DOM structure.

**Comment by danielimmke** [comment]
Hey, I will try to post something later today. Thanks for the super quick response times y'all!

**Comment by danielimmke** [comment]
Hey, I looked more into it and yes the DOM changes. Gives me a good opportunity to dig deeper into event delegation! Thanks for the tip.
