### ISSUE TITLE
Increase scroll responsiveness

### ISSUE THREAD

**Issue by benjaminlim00** [alvarotrigo/react-fullpage#217]
### Description
Can i check if there is a way to remove the delay between each page scroll? I have reduced the scroll speed by setting
 `scrollingSpeed={400}`
but however, there is still a delay in between each scroll which causes the page to feel unresponsive when attempting to scroll to the last page quickly. Is there another setting I can experiment with?

**Comment by alvarotrigo** [comment]
> but however, there is still a delay in between each scroll which causes the page to feel unresponsive when attempting to scroll to the last page quickly. Is there another setting I can experiment with?

The delay is intentional as  a way to avoid double or triple scrolling on kinetic scrolling devices such as Macbook trackpads, Apple magic mouses and other devices.

See these topics
https://github.com/alvarotrigo/fullPage.js/pull/3826
https://github.com/alvarotrigo/fullPage.js/issues/2921
https://github.com/alvarotrigo/fullPage.js/issues/2407
https://github.com/alvarotrigo/fullPage.js/issues/3995
