### ISSUE TITLE
How to use extensions with Next.js

### ISSUE THREAD

**Issue by Contengo** [alvarotrigo/react-fullpage#222]
### I can't find an example of using the extensions with Next.js

Hi - I just purchased the extensions pack: I'm trying to use parallax in a Next.js project. What I need to know is...

1.  Physically where in the folder structure should I put the fullpage.parallax.min.js file?
2.  How do I then link it in?

I tried putting it in the 'Static' folder from the Next.js fullpage example show in the examples, and linking it like this...

`const pluginWrapper = () => {
  require('/static/fullpage.parallax.min');
};`

...but it can't resolve that location.

**Comment by alvarotrigo** [comment]
Good point! Apparently we forgot to add an example on Next.js example files.
You'll have to use the variable `pluginWrapper` as stated [on the docs](https://github.com/alvarotrigo/react-fullpage#examples).

I've just added an example with it on [this commit](https://github.com/alvarotrigo/react-fullpage/commit/29b1381535b12c6229c97c70a404257bf0fd2c7a).

You can see the whole file on the dev branch:
https://github.com/alvarotrigo/react-fullpage/blob/dev/examples/next/pages/index.js

You can check the whole Next.js example here:
https://github.com/alvarotrigo/react-fullpage/blob/dev/examples/next/

> Physically where in the folder structure should I put the fullpage.parallax.min.js file?

In my example I assume the extension file `fullpage.scrollHorizontally.min.js` is on the `static` folder, that's why I import using the following:

```js
const pluginWrapper = () => {
  require('../static/fullpage.scrollHorizontally.min.js'); // Optional. Required when using the "scrollHorizontally" extension.
};
``` 

Make sure you do not forget to also use the appropiate option in fullpage.js initialisation, in this case `scrollHorizontally:true`.

**Comment by Contengo** [comment]
Perfect – many thanks!

Charles

**Comment by alvarotrigo** [comment]
No problem! 👍
