### ISSUE TITLE
Overriding default styles of navigation is not working after creating build.

### ISSUE THREAD

**Issue by anshuraj** [alvarotrigo/react-fullpage#45]
I want to customise the navigation using css, it doesn't work when I create build. It works in development. Is there any option to override the default class/id iof the navigation for custom styles?

**Comment by alvarotrigo** [comment]
The build includes the fullPage CSS file by default.
Perhaps you can consider removing the CSS from the build file by removing the following line in `components/React-fullpage/index.js`:

```javascript
import fullpageStyles from 'fullpage.js/dist/fullpage.min.css'; // eslint-disable-line no-unused-vars
```

Then build it again yourself, include the CSS file as normal and overwrite those with your own ones by including your css file after it:

```html
<link rel="stylesheet" type="text/css" href="fullpage.css" />
<link rel="stylesheet" type="text/css" href="my-overwrites.css" />
```

**Comment by cmswalker** [comment]
Since styles are baked in and are being applied in the JS runtime by creating a stylesheet on the fly, it's likely overriding your custom css since it loads 2nd. This may be a good reason to consider either A. not bundling the styles or B. providing an example in the docs of overrides. It's a bit limiting but your easiest option would be to load the stylesheet in javascript, after your fullpage.js code has been initialized, that will give you the overrides you need.

**Comment by camp54** [comment]
I realize this is slightly old, but experiencing this same issue where overrides specified in the override.css file are not properly reflected after a build (Gatsby).  Is the recommendation from @alvarotrigo above still the proper approach?  I'm leveraging Tailwind for the bulk of the site, so in that case would I import the fullpage.css file in the gatsby-browser.js file - and leave the override.css to be imported in either a page or component?
